version: '3.6'
services:             
    nats-server:
      image: nats:latest
      container_name: nats-server
      ports:
        - "4222:4222"
        - "6222:6222"
        - "8222:8222"

    mongo-raw:
      image: mongo
      container_name: mongo-raw
      restart: always
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: footballiot
        MONGO_INITDB_ROOT_PASSWORD: footballiot

    mongo-raw-gui:
      image: mongo-express
      container_name: mongo-raw-gui
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: footballiot
        ME_CONFIG_MONGODB_ADMINPASSWORD: footballiot
        ME_CONFIG_MONGODB_URL: mongodb://footballiot:footballiot@mongo-raw:27017/

    mongo-modified:
      image: mongo
      container_name: mongo-modified
      restart: always
      ports:
        - 27018:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: footballiot
        MONGO_INITDB_ROOT_PASSWORD: footballiot

    mongo-modified-gui:
      image: mongo-express
      container_name: mongo-modified-gui
      restart: always
      ports:
        - 8082:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: footballiot
        ME_CONFIG_MONGODB_ADMINPASSWORD: footballiot
        ME_CONFIG_MONGODB_URL: mongodb://footballiot:footballiot@mongo-modified:27017/
    
    grafana:
      image: grafana/grafana-enterprise
      ports:
        - 3000:3000
    
    postgre-raw:
      image: postgres
      container_name: postgres-raw
      environment: 
          - DATABASE_HOST=localhost
          - POSTGRES_USER=footballiot
          - POSTGRES_PASSWORD=footballiot
      ports: 
            - "5532:5432"
      volumes: 
            - ./01_postgres_create_tables.sql:/docker-entrypoint-initdb.d/01_postgres_create_tables.sql

    pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"

