version: '3.6'
services:             
    nats-server:
      image: nats:latest
      container_name: nats-server
      environment:
        - ORACLE_ALLOW_REMOTE=true
      ports:
        - "4222:4222"
        - "6222:6222"
        - "8222:8222"

    mongo:
      image: mongo
      container_name: mongo-db
      ports:
        - 27017:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: footballiot
        MONGO_INITDB_ROOT_PASSWORD: footballiot

    mongo-express:
      container_name: mongo-gui
      image: mongo-express
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: footballiot
        ME_CONFIG_MONGODB_ADMINPASSWORD: footballiot
        ME_CONFIG_MONGODB_URL: mongodb://footballiot:footballiot@mongo:27017/