version: '3.6'
services:             
    nats-server:
      image: nats:latest
      container_name: nats-server
      environment:
        - ORACLE_ALLOW_REMOTE=true
      ports:
        - "4222:4222"
        - "6222:6222"
        - "8222:8222"
